### PR TITLE
Few devDependency upgrades

### PR DESCRIPTION
**Pull request by koresar**
* Remove annoying dependency - eslint-config-airbnb-base
* Upgrade some devDependencies.
* The eslint-plugin-import was never used! Turned in on.

### CODE REVIEW

**Comment by FredyC** [comment]
Annoying dependency? I don't get it. It contains many useful rules you have simply disabled with this. Also import plugin was used and configured with airbnb.

**Comment by koresar** [comment]
Every time it upgrades - something breaks. :(

**Comment by FredyC** [comment]
That's not true. There was this incompatibility with import plugin, but that's fixed for some now.

Also I don't understand how could there be so many outdated dependecies, I thought greenkeeper is watching it or did you disabled it?

**Comment by koresar** [comment]
I did not. Greenkeeper doesn't do it's job good enough.

**Pull request closed without merging**
