### PR TITLE
Remove "browser" property from package.json as not needed and wrongly used

### PR DESCRIPTION
**Pull request by koresar**

### CODE REVIEW

**Comment by FredyC** [comment]
@koresar Can you please make a new release with this? Thanks :)

**Comment by koresar** [comment]
Easy. Let me get to a computer.

**Comment by FredyC** [comment]
@koresar Umm...bump? :)

**Comment by koresar** [comment]
Done. I'm so sorry about forgetting to do it earlier.

**Comment by FredyC** [comment]
Thanks, it's fine :)

**Pull request merged**
