### PR TITLE
Enable Loose Mode

### PR DESCRIPTION
**Pull request by abhisekp**
**Reference**: http://www.2ality.com/2015/12/babel6-loose-mode.html

- Decreases size by removing redundant ES5 code generation

### CODE REVIEW

**Comment by koresar** [comment]
I should mention that in the current state this change might not decrease the distribution size. Although, chances are that will be helpful in the future.

**Comment by FredyC** [comment]
Personally I don't understand why we are even listing all those plugins there when we are not using all of them. It might even give us faster builds if we are more selective about features we actually need.

**Comment by koresar** [comment]
Moreover, I don't understand why we are even using ES6 we are limiting ourselves to certain set of ES6 features? We could ditch babel altogether. :)

**Comment by FredyC** [comment]
I would not ditch ES6 modules a probably some spread or destructuring make things more readable. I am wondering. Check out the result of [loose transpilation of stampit.js](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015-loose&experimental=true&loose=false&spec=false&code=import%20standardiseDescriptor%20from%20'.%2Fstandardise-descriptor'%3B%0Aimport%20extractFunctions%20from%20'.%2Fextract-functions'%3B%0Aimport%20merge%20from%20'.%2Fmerge'%3B%0Aimport%20compose%20from%20'.%2Fcompose'%3B%0Aimport%20isComposable%20from%20'.%2FisComposable'%3B%0Aimport%20isStamp%20from%20'.%2FisStamp'%3B%0A%0Aconst%20assign%20%3D%20Object.assign%3B%0A%0Afunction%20createUtilityFunction(propName%2C%20action)%20%7B%0A%20%20return%20function%20composeUtil()%20%7B%0A%20%20%20%20const%20descriptor%20%3D%20%7B%7D%3B%0A%20%20%20%20descriptor%5BpropName%5D%20%3D%20action(%7B%7D%2C%20...arguments)%3B%0A%20%20%20%20return%20((this%20%26%26%20this.compose)%20%7C%7C%20stampit).call(this%2C%20descriptor)%3B%0A%20%20%7D%3B%0A%7D%0A%0Aexport%20const%20methods%20%3D%20createUtilityFunction('methods'%2C%20assign)%3B%0A%0Aexport%20const%20properties%20%3D%20createUtilityFunction('properties'%2C%20assign)%3B%0Aexport%20%7Bproperties%20as%20refs%7D%3B%0Aexport%20%7Bproperties%20as%20props%7D%3B%0A%0Aexport%20function%20initializers(...args)%20%7B%0A%20%20return%20((this%20%26%26%20this.compose)%20%7C%7C%20stampit).call(this%2C%20%7B%0A%20%20%20%20initializers%3A%20extractFunctions(...args)%0A%20%20%7D)%3B%0A%7D%0Aexport%20%7Binitializers%20as%20init%7D%3B%0A%0Aexport%20const%20deepProperties%20%3D%20createUtilityFunction('deepProperties'%2C%20merge)%3B%0Aexport%20%7BdeepProperties%20as%20deepProps%7D%3B%0A%0Aexport%20const%20staticProperties%20%3D%20createUtilityFunction('staticProperties'%2C%20assign)%3B%0Aexport%20%7BstaticProperties%20as%20statics%7D%3B%0A%0Aexport%20const%20staticDeepProperties%20%3D%20createUtilityFunction('staticDeepProperties'%2C%20merge)%3B%0Aexport%20%7BstaticDeepProperties%20as%20deepStatics%7D%3B%0A%0Aexport%20const%20configuration%20%3D%20createUtilityFunction('configuration'%2C%20assign)%3B%0Aexport%20%7Bconfiguration%20as%20conf%7D%3B%0A%0Aexport%20const%20deepConfiguration%20%3D%20createUtilityFunction('deepConfiguration'%2C%20merge)%3B%0Aexport%20%7BdeepConfiguration%20as%20deepConf%7D%3B%0A%0Aexport%20const%20propertyDescriptors%20%3D%20createUtilityFunction('propertyDescriptors'%2C%20assign)%3B%0A%0Aexport%20const%20staticPropertyDescriptors%20%3D%20createUtilityFunction('staticPropertyDescriptors'%2C%20assign)%3B%0A%0Aconst%20allUtilities%20%3D%20%7B%0A%20%20methods%2C%0A%0A%20%20properties%2C%0A%20%20refs%3A%20properties%2C%0A%20%20props%3A%20properties%2C%0A%0A%20%20initializers%2C%0A%20%20init%3A%20initializers%2C%0A%0A%20%20deepProperties%2C%0A%20%20deepProps%3A%20deepProperties%2C%0A%0A%20%20staticProperties%2C%0A%20%20statics%3A%20staticProperties%2C%0A%0A%20%20staticDeepProperties%2C%0A%20%20deepStatics%3A%20staticDeepProperties%2C%0A%0A%20%20configuration%2C%0A%20%20conf%3A%20configuration%2C%0A%0A%20%20deepConfiguration%2C%0A%20%20deepConf%3A%20deepConfiguration%2C%0A%0A%20%20propertyDescriptors%2C%0A%0A%20%20staticPropertyDescriptors%0A%7D%3B%0A%0A%2F**%0A%20*%20Infected%20stamp.%20Used%20as%20a%20storage%20of%20the%20infection%20metadata%0A%20*%20%40type%20%7BFunction%7D%0A%20*%20%40return%20%7BStamp%7D%0A%20*%2F%0Aconst%20baseStampit%20%3D%20compose(%0A%20%20%7BstaticProperties%3A%20allUtilities%7D%2C%0A%20%20%7B%0A%20%20%20%20staticProperties%3A%20%7B%0A%20%20%20%20%20%20create(...args)%20%7B%0A%20%20%20%20%20%20%20%20return%20this(...args)%3B%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20compose%3A%20stampit%20%2F%2F%20infecting%0A%20%20%20%20%7D%0A%20%20%7D%0A)%3B%0A%0A%2F**%0A%20*%20Infected%20compose%0A%20*%20%40return%20%7BStamp%7D%0A%20*%2F%0Afunction%20stampit(...args)%20%7B%0A%20%20args%20%3D%20args.filter(isComposable)%0A%20%20%20%20.map(arg%20%3D%3E%20isStamp(arg)%20%3F%20arg%20%3A%20standardiseDescriptor(arg))%3B%0A%0A%20%20%2F%2F%20Calling%20the%20standard%20pure%20compose%20function%20here.%0A%20%20return%20compose.apply(this%20%7C%7C%20baseStampit%2C%20args)%3B%0A%7D%0A%0Aconst%20exportedCompose%20%3D%20stampit.bind()%3B%20%2F%2F%20bind%20to%20'undefined'%0Aexport%20%7BexportedCompose%20as%20compose%7D%3B%0Astampit.compose%20%3D%20exportedCompose%3B%0A%0A%2F%2F%20Setting%20up%20the%20shortcut%20functions%0Aexport%20default%20assign(stampit%2C%20allUtilities)%3B%0A)

**Comment by FredyC** [comment]
I would say it's kinda endless debate on rewriting stuff to ES5, but I still don't think it's a good idea. There is more environments that can actually support ES6 than there is those that don't support it. I don't have any proof for it, but I would say that some constructs will be faster executed natively. For example this simple line of code: 

`descriptor[propName] = action({}, ...arguments);`

Even in "loose" mode it is transpiled to: 

descriptor[propName] = action.apply(undefined, [{}].concat(Array.prototype.slice.call(arguments)));

That looks like hell kinda. However it's essentially correct by ES5 capabilities. In ES6 engine it's possible that this would be optimized differently.

**Comment by koresar** [comment]
Totally agree with everything you say.

There's just one "but". We **have to** support older environments. In other words, we have to transpile down to ES5.

**Comment by FredyC** [comment]
Yes we do transpile. Currently it's necessary step to make everyone happy. But eventually this might not be needed anymore and I doubt we will be rewriting back from ES5 to ES6 after it. I see it like supporting the future this way. The more modules in ES6 there is, faster will people leave behind obsolete platforms in my opinion.

**Pull request merged**
