### PR TITLE
Typescript support

### PR DESCRIPTION
**Pull request by PopGoesTheWza**
# Issue #245 [Work In Progress]

## A more advanced version of `stampit` types

There is a "DefinitelyTyped" style `tests.ts` file which illustrate basic `stampit` usage under typescript.

### CODE REVIEW

**Comment by koresar** [comment]
Is it still WIP?

**Comment by PopGoesTheWza** [comment]
Currently awaiting review and proposal for testing.

**Comment by koresar** [comment]
@PopGoesTheWza I've sent an invite to you to join the stampit-org collaborators. Now you can clone https://github.com/stampit-org/stampit.git repo and push straight to it. 
So, in the future if you are creating any more PRs I'd recommend creating a branch in this stampit-org/stampit repo instead of your own fork.

**Comment by PopGoesTheWza** [comment]
@koresar holding on committing types tests as I run into an [issue](https://github.com/microsoft/dtslint/issues/257) with latest version of `dtslint`

**Comment by koresar** [comment]
Tell me when it's ready to merge. :) Or merge yourself when you think it's ready to go. I'll publish.

**Comment by PopGoesTheWza** [comment]
@koresar We could merge it right now with the following implications:

- the DT `@types/stampit` would become obsolete (i.e. only useful when using version of `stampit` prior 4.3
- no unit tests for types at the moment (I have a test suite "à la" DT ready but it require an update of the `dtslint` package.)

**Comment by koresar** [comment]
Sounds good to me! Go ahead. Merge it.
I'll do release notes after that.

Do you believe it better be realised as v4.4 or v4.3.1?

**Comment by PopGoesTheWza** [comment]
4.4 I'd say.
Sample TS might be necessary?

**Comment by koresar** [comment]
Sorry, what's "Sample TS"? And where this needs to be better put?

**Comment by PopGoesTheWza** [comment]
I meant sample typescript code. It could be some doc/typescript.md file, a wiki entry, a fun with stamp post. Your pick.

**Comment by koresar** [comment]
Do whatever you think is the best for the community and easiest for you.

I'd recommend going for:
* README.md update (convert the "What's the Point?" code to TS)
* We don't have Wiki, but we have stampit.js.org documentation website. I will give you access to use its builtin WYSIWYG editor.
* A Fun With Stamps post too.

Take into account, that my time is quite limited currently as I have 23 days old [baby](https://www.instagram.com/p/B3YkdBDAVUn/). :)

**Comment by koresar** [comment]
I need to send you an invite link to the stampit.js.org docs editor.
Please DM me in twitter (kore_sar) or email kore.sar on gmail.

**Comment by koresar** [comment]
Released as v4.3.1 🎉 

https://github.com/stampit-org/stampit/releases/tag/v4.3.1

**Comment by char0n** [comment]
Hi guys, 

I have question regarding Typescript usage of stamps.

```js
interface Type {
  prop: string;
}

const Type: stampit.Stamp<Type> = stampit({ 
  statics: {
    of(value) {
      return Type({ prop: value });
    }
  },
  props: {
    prop: ''
  },
  init({ prop }) {
    this.prop = prop;
  }
});

Type.of(1); // Property of doesn't exist on type Stamp
```

Not sure If what I'm doing is correct and have no idea how to properly use static `of` function for the `Type` stamp. I didn't find any documentation on TypeScript + Stamps. Could you guys clarify please?

**Comment by koresar** [comment]
Your usage is correct if done with JavaScript. TypeScript support is lagging behind. There was a great push a year ago. But it was not finished. Unfortunately.

I'd recommend `any` at this stage.

Rant: TypeScript has the same mistake as many other languages - it uses classes and inheritance. The stamps were invented specifically to overcome the limitations of classes (hence you have the error). Bridging two together is possible, but very very hard due to TS design.

**Comment by char0n** [comment]
@koresar thanks

**Pull request merged**
