### PR TITLE
Tracing property overwrites

### PR DESCRIPTION
**Pull request by koresar**
RDD - Readme Driven Development. First demo commit.

Please, assess and comment. If the approach is okay I'll proceed the development.

### CODE REVIEW

**Comment by ericelliott** [comment]
Personally, I don't care about property name collisions -- with the defaults/overrides pattern, that is a common and expected situation.

What I want to be notified about is if `propTypes` conflict when I pass stamps into `stampit.compose()`.

**Comment by koresar** [comment]
That's something new to me.

Okay, again. How do you see an API? Without you answering this question I keen to abandon this task/feature. **I literally do not know what you guys want.** :)))))))

/cc @troutowicz

**Comment by ericelliott** [comment]
=)

**Comment by ericelliott** [comment]
Let's close this and open a new one later when requirements are fleshed out better. =)

**Pull request closed without merging**
