### PR TITLE
meteor package for stampit #138

### PR DESCRIPTION
**Pull request by yasinuslu**
I have implemented initial version of meteor package. Ref: #138

### CODE REVIEW

**Comment by ericelliott** [comment]
I'm not convinced that this belongs in the Stampit repository. Maybe it should be in a separate repo that wraps this one?

**Comment by koresar** [comment]
Agree on separate repo. Will you create one Eric? And maybe even give @yasinuslu the writing permission.

**Comment by yasinuslu** [comment]
Wrapper packages for both bootstrap and moment (only official packages i recall) resides in the original repo so i thought it was logical.

https://github.com/twbs/bootstrap/blob/master/package.js
https://github.com/moment/moment/tree/master/meteor

Package doesn't use any files from this repository so there is no problem separating it.

**Comment by ericelliott** [comment]
See [stampit-meteor](https://github.com/stampit-org/stampit-meteor)

**Pull request closed without merging**
