### PR TITLE
Drop those old-timey bower peeps on the floor. Who needs bower?

### PR DESCRIPTION
**Pull request by ericelliott**

### CODE REVIEW

**Comment by koresar** [comment]
`./dist/stampit.js` should be `./stampit.js`

**Comment by ericelliott** [comment]
I don't think so. Bower expects AMD or UMD. ./stampit.js is not either of those things.

**Comment by koresar** [comment]
Oh, we don't have this file regardless. Time to drop bower support?

**Comment by sethlivingston** [comment]
The unfortunate side effect of this is that it prevents libraries that still use bower from listing stampit as a dependency. Bower support is best dropped from apps -> frameworks -> libraries, not the other way around.

**Comment by koresar** [comment]
@sethlivingston Hey, Seth, how are you?

Would you help us to maintain the bower package?

**Comment by sethlivingston** [comment]
I'd be happy to, but I know @ericelliott is wanting to push the universal javascript message (no bower)--which I respect. If you guys decide you want to keep it for now, I'd be happy to maintain it.

**Comment by koresar** [comment]
:)))
I believe, if you needed stampit v2 on bower, then more people would need it. I doubt Eric would be against.

@ericelliott Can you pass on the stampit bower credentials to this handsome gentleman?

**Comment by ericelliott** [comment]
I have no bower credentials to bestow. I'm not the one who managed the power package. If it's coming back, someone will need to create a new Bower package.

:facepalm:

**Comment by ericelliott** [comment]
That totally needs to be an emoji.

**Comment by koresar** [comment]
We got to find the person who published it to bower the first.

**Comment by ericelliott** [comment]
Good times... ;)

**Comment by sethlivingston** [comment]
Haha okay I'm on it. I'll pass along an update tomorrow...

**Comment by koresar** [comment]
Do we have any progress on brew, @sethlivingston ?

**Comment by sethlivingston** [comment]
Not yet, but I will get this submitted. I need it. Few more days...

**Comment by koresar** [comment]
no worries! Thanks for that!

**Comment by sethlivingston** [comment]
This is working fine as it is, guys.

    bower install stampit

installs stampit 2.1.0 (the latest as of this writing), and

    bower install stampit#1.2.0

installs stampit 1.2.0. I honestly could not tell you why it wasn't working for me before, but it works fine now.

We *do* need to restore the bower.json file, though. I will submit a PR momentarily for that...

**Comment by sethlivingston** [comment]
...https://github.com/stampit-org/stampit/issues/150 needs to be resolved first.

**Comment by sethlivingston** [comment]
And to clarify an earlier comment on this thread, Bower doesn't care what type of module you publish--AMD, UMD, globals, ... doesn't matter. Bower's main goal is to make it easier for developers to get the files they need quickly and (presumably) bundle them.

**Comment by ericelliott** [comment]
Do we need to open a new issue and get some movement on this? @sethlivingston run with it. Getting Stampit to play nice with bower is all yours. =)

**Pull request merged**
