### PR TITLE
Real life example in readme

### PR DESCRIPTION
**Pull request by koresar**
Trying to achieve that sort of a readme: https://github.com/stampit-org/stampit/issues/122#issuecomment-118570103

### CODE REVIEW

**Comment by JosephClay** [comment]
ES6 looks good, but I find the silly example is more clear to me than the real life. Personal preference.

**Comment by koresar** [comment]
@JosephClay Good to hear that! I appreciate your honesty. :)
Can you try and scrub your feelings regarding the two and tell us **why** silly is better?

**Comment by koresar** [comment]
I'm merging this in 8 hours. :) Alright?

**Comment by ericelliott** [comment]
I also think the silly example is more clear. The problem with a real life example is that people have a harder time imagining how to apply it to their own problems. Real life examples should stay in the advanced examples, IMO.

**Comment by ericelliott** [comment]
I do like the ES6 updates, though. Want to remove the real life bit and just merge the ES6 upgrade?

**Comment by troutowicz** [comment]
> Real life examples should stay in the advanced examples

Agreed. :)

**Comment by koresar** [comment]
Ok. Sure.

**Comment by koresar** [comment]
Looks like all good. :)

**Pull request merged**
