### PR TITLE
Api doc

### PR DESCRIPTION
**Pull request by koresar**
Created a new directory `docs`. Copied text from `README.md` to the new `API.md`.
Added one simple but useful example at the top.

### CODE REVIEW

**Comment by troutowicz** [comment]
Can we remove this documentation from the README and add a link to this API doc? It might be better to include the example in the README, and link to the API doc for more information.

**Comment by koresar** [comment]
Sure we can an we will with the following PRs. One thing at a time Tim.
Also, you can merge this one and create a new one with the changes you've
just proposed.

Is this API.md okay to merge?

**Comment by ericelliott** [comment]
Looks OK to me.

**Comment by koresar** [comment]
Sorry for the numerous typos. I was in a hurry. :)

**Comment by ericelliott** [comment]
Sorry I merged the typos. I was in a hurry.

**Comment by koresar** [comment]
:) The typos are in this issue. But the changes got not typos (hopefully). :)

**Comment by troutowicz** [comment]
> One thing at a time Tim.

:scream_cat:

**Pull request merged**
