### PR TITLE
feat: add version number to Stampit API

### LINKED ISSUE #332: ✨ Add .version to stampit object
My story: I just got back again to my old project that uses stampit after leaving it for 3+ years. I was confused for quite some time because I forgot which stampit version I used (was it 2.x or was it 3.x?). The frontend libraries of this project weren't managed by bower/npm, so... 😅 

I guess it would be useful if version information could be added to the API like `angular.version`, `React.version`, `lodash.VERSION`, etc.?

### PR DESCRIPTION
**Pull request by dwiyatci**
This should close #332.

### CODE REVIEW

**Comment by FredyC** [comment]
I think this needs some sort of automation as a part of release process or at least document it somewhere. But that's just my point of view. It's up the @koresar who is making releases if he will be able to remember updating that number there manually.

**Comment by koresar** [comment]
Yeah. I don't trust myself much. Automation would help significantly.

The 'npm run build' would need to have one more command to replace the "STAMPIT_VERSION" steering in the minified bundle with whatever is in the package.json.version. And the source code would need to have ".version = 'STAMPIT_VERSION'".

If sounds too complicated for you Glenn, I can do it myself today evening. (currently morning in Australia)

**Comment by koresar** [comment]
Oh, hold on... That wouldn't work. Need to think a little.

**Comment by dwiyatci** [comment]
Right. Automation FTW! 

And yes, please. Feel free to decline this PR and take it over, Vasyl. I don't think I have too much spare time these days 🙃

**Comment by koresar** [comment]
PR #334 created.

Thanks @dwiyatci 
Btw, you created PR number 333. Congrats on that smoosh number!

**Pull request closed without merging**
