### PR TITLE
Fix links for stamp.init() and stamp.composers() in API documentation TOC.

### PR DESCRIPTION
**Pull request by fpoumian**
I noticed some of the links in the API documentation TOC were either wrong or missing, so I just ran Doctoc on API.md and that fixed it.

### CODE REVIEW

**Comment by koresar** [comment]
So much thank you!

**Comment by koresar** [comment]
We are an open community. Would you like to be added to the organisation people list?
https://github.com/orgs/stampit-org/people

**Comment by fpoumian** [comment]
Sure! :)

**Comment by koresar** [comment]
Invite sent 👍 
:)
Welcome!

**Comment by fpoumian** [comment]
Invite accepted. Thanks a lot!

**Pull request merged**
