### PR TITLE
Add react-stampit link to README

### PR DESCRIPTION
**Pull request by ericelliott**

### CODE REVIEW

**Comment by troutowicz** [comment]
Nice!

**Comment by koresar** [comment]
This is good to mentions react-stampit. But the placement of the text is rather too high. React is somewhat irrelevant to our main objective - the stamps. In my opinion, this text should go somewhere below "What is a Stamp" section.

**Comment by koresar** [comment]
@troutowicz You were too fast to merge. :)

Nevertheless, should we move the React mention lower?

**Comment by troutowicz** [comment]
I merged simply because everyone has pretty much agreed the README needs a rewrite. Figured just having the mention for now wherever was fine.

**Comment by koresar** [comment]
I believe that making README worse just before making a large blog post about stampit is not wise. Can we at least minimize the bloating impact?

Just use **bold** instead of h3. See below.

-----

**React Users.** Stampit loves React. Check out [react-stampit](https://github.com/stampit-org/react-stampit) for composable components.

**Comment by troutowicz** [comment]
I don't consider the placement bad to be honest. The placement should be close enough to the top and noticeable enough for anyone to see without having to scroll through API related docs.

But your change would probably be noticeable enough.

**Comment by koresar** [comment]
@troutowicz see #124

**Pull request merged**
