### PR TITLE
Export isComposable and isStamp separately

### PR DESCRIPTION
**Pull request by FredyC**
Based on [#209](https://github.com/stampit-org/stampit/pull/209#issuecomment-222907611)

I am not much of a fan of having source file outside of src folder, but I guess this is best way for greater good.

/cc @ericelliott @koresar

### CODE REVIEW

**Comment by ericelliott** [comment]
LGTM.

**Comment by koresar** [comment]
@FredyC Do you know that you can create branches in `stampit-org` repo? No need to implement things in your forks. You're a collaborator. :)

**Comment by FredyC** [comment]
I know, but I am more used to forks and I have set of git aliases for that. It seems bit cleaner way to me too.

**Comment by koresar** [comment]
It's just more complex for the rest of the people to collaborate. I.e. we can't fix up your branch on a fly. The conflict resolution becomes a pain in the neck too. Also, it's longer to pull the fork and test it then a branch.
But, as long as you prefer forks we all can leave with that for sure.

**Pull request merged**
