### PR TITLE
Support automatic releases to CDNJS

### PR DESCRIPTION
**Pull request by nkbt**
See https://github.com/ericelliott/prod-module-boilerplate/issues/18

When this is merged, PR to https://github.com/cdnjs/cdnjs/ should be made (with cdnjs-importer tool), so the existing stampit there is updated with new config. Then every new NPM release will be automatically published on CDNJS.

### CODE REVIEW

**Comment by troutowicz** [comment]
This is cool. :+1:

**Comment by ericelliott** [comment]
https://github.com/cdnjs/cdnjs/pull/4776

**Comment by nkbt** [comment]
https://github.com/cdnjs/cdnjs/pull/4778 this one is correct. Until you publish npm, tool cannot pick correct package.json. I made changes manually, so the submission is valid.

**Comment by nkbt** [comment]
Took ages to apply those changes in such a massive cdnjs repo.

**Pull request merged**
